CREATE TABLE
  public.gender_categories (
    id BIGINT GENERATED ALWAYS AS IDENTITY NOT NULL,
    gender TEXT NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITH TIME ZONE NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT gender_categories_pkey PRIMARY KEY (id)
  ) TABLESPACE pg_default;